module.exports = {

  AddedUserToAdmin: require('./src/admin/AddedUserToAdmin'),
  BuildInfo: require('./src/admin/BuildInfo'),
  ExecutedCommandOfAdmin: require('./src/admin/ExecutedCommandOfAdmin'),
  ListDatabases: require('./src/admin/ListDatabases'),
  Ping: require('./src/admin/Ping'),
  RemovedUserFromAdmin: require('./src/admin/RemovedUserFromAdmin'),
  ReplicaSetStatus: require('./src/admin/ReplicaSetStatus'),
  ServerInfo: require('./src/admin/ServerInfo'),
  ServerStatus: require('./src/admin/ServerStatus'),
  ValidatedCollection: require('./src/admin/ValidatedCollection'),

  AddedUserToDb: require('./src/db/AddedUserToDb'),
  AdminOfDb: require('./src/db/AdminOfDb'),
  CollectionOfDb: require('./src/db/CollectionOfDb'),
  CollectionsOfDb: require('./src/db/CollectionsOfDb'),
  CreatedCollection: require('./src/db/CreatedCollection'),
  CreatedIndexByDb: require('./src/db/CreatedIndexByDb'),
  DbStats: require('./src/db/DbStats'),
  DbWithProfilingLevel: require('./src/db/DbWithProfilingLevel'),
  DroppedCollection: require('./src/db/DroppedCollection'),
  DroppedDatabase: require('./src/db/DroppedDatabase'),
  ExecutedCommandOfDb: require('./src/db/ExecutedCommandOfDb'),
  ExecutedDbAdminCommand: require('./src/db/ExecutedDbAdminCommand'),
  IndexInformationByDb: require('./src/db/IndexInformationByDb'),
  ListCollections: require('./src/db/ListCollections'),
  ProfilingLevel: require('./src/db/ProfilingLevel'),
  RemovedUserFromDb: require('./src/db/RemovedUserFromDb'),
  RenamedCollection: require('./src/db/RenamedCollection'),
  UnrefDb: require('./src/db/UnrefDb'),
  WatchedDb: require('./src/db/WatchedDb'),

  ChangeStreamOfMongoClient: require('./src/mongo-client/ChangeStreamOfMongoClient'),
  ClosedMongoClient: require('./src/mongo-client/ClosedMongoClient'),
  ConnectedMongoClient: require('./src/mongo-client/ConnectedMongoClient'),
  DbOfMongoClient: require('./src/mongo-client/DbOfMongoClient'),
  IsConnected: require('./src/mongo-client/IsConnected'),
  LoggedOutMongoClient: require('./src/mongo-client/LoggedOutMongoClient'),
  MongoClientWithSession: require('./src/mongo-client/MongoClientWithSession'),
  StartedSession: require('./src/mongo-client/StartedSession')

}
